### ISSUE TITLE
scrollNode.scrollTo is not a function

### ISSUE THREAD

**Issue by partitect** [netguru/sticky-parallax-header#102]
I am waiting for this problem to be solved in fixed to use this plugin

**Comment by bro-jo** [comment]
me too

**Comment by bro-jo** [comment]
Seems to be related to https://github.com/facebook/react-native/issues/19235

**Comment by bro-jo** [comment]
https://github.com/netguru/sticky-parallax-header/pull/105
I think this will solve the problem.

**Comment by pwysowski** [comment]
Issue was fixed in #106
