### ISSUE TITLE
Is there a relative easy way to combine AvatarHeader and TabbedHeader?

### ISSUE THREAD

**Issue by Kleinhummel** [netguru/sticky-parallax-header#103]
I would like to have the AvatarHeader as the header but with the tabs at the bottom...I already started exploring the source code but I am a little overwhelmed of all the components and the interaction between them. A quick explanation of how to get what I want would be awesome!

**Comment by AakashPat** [comment]
I am looking to do the exact same thing that you have mentioned. Still have been unable to get my head around.

**Comment by Relax594** [comment]
a little more customizability in this predefined components would be awesome yeah. Like custom titleStyle, subtitleStyle, custom icons top left and right (not just an image source). Even changing the subtitle to taking a react-element would help a lot actually.

**Comment by pi0trpietruszewski** [comment]
@Kleinhummel You can always create custom header [Blogpost about custom header](https://www.netguru.com/codestories/implement-an-app-store-header-in-react-native-with-sticky-parallax-library) or [Doc example](https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md)

Also feel free to make a contribution :D

**Comment by phuongwd** [comment]
huhu guys :)
> the tabs at the bottom.

![bottom-tabs](https://user-images.githubusercontent.com/2460806/100682044-bdb14b00-33a7-11eb-91e2-04bf79497d92.gif)
