### ISSUE TITLE
Reset to first tab

### ISSUE THREAD

**Issue by burhanahmed92** [netguru/sticky-parallax-header#104]
How can I reset my sticky tabbed header to the initial position? I mean selecting the first tab by default. Usually, this issue occurs when I select tab number 3 or 4 and go to another screen and then come back. it still selects those tabs. I want to know is there a way to call a method that selects the first tab by default onFocus. I set up the focus method but I am unable to find any property in this library that can do that. Kindly guide

**Comment by pwysowski** [comment]
Feature added in #111
