### ISSUE TITLE
renderBody property doesn't work

### ISSUE THREAD

**Issue by KamranKhan-Dev** [netguru/sticky-parallax-header#116]
Hello, 

I'm aware of issue #39 , however, I don't feel that a solution was provided.

Regardless of what you pass into the `renderBody` property, the default "Mornin' Mark! Ready for a quiz?" component is displayed.

I appreciate that this can be overwritten using the backgroundImage and foregroundImage as per the Yoda example, but it doesn't show how you can render your own component instead.

**Comment by AakashPat** [comment]
I am also trying to figure out this exact same thing.

When you set headerType as `headerType="AvatarHeader"` we can pass a custom component using the foreground property in order to customize the content of the section. But when we set the headerType as `headerType="TabbedHeader"`, we are unable to pass a custom component, and thus we are stuck with the default layout in which we can only change the image and the title.

There has to be a way to be able to pass a custom component for `headerType="TabbedHeader"` as well.

**Comment by AakashPat** [comment]
> Hello,
> 
> I'm aware of issue #39 , however, I don't feel that a solution was provided.
> 
> Regardless of what you pass into the `renderBody` property, the default "Mornin' Mark! Ready for a quiz?" component is displayed.
> 
> I appreciate that this can be overwritten using the backgroundImage and foregroundImage as per the Yoda example, but it doesn't show how you can render your own component instead.

Please check this link: https://github.com/netguru/sticky-parallax-header/blob/HEAD/docs/CUSTOM.md

I have managed to create a custom header using the code as example on the above link.

**Comment by sorxrob** [comment]
> > Hello,
> > I'm aware of issue #39 , however, I don't feel that a solution was provided.
> > Regardless of what you pass into the `renderBody` property, the default "Mornin' Mark! Ready for a quiz?" component is displayed.
> > I appreciate that this can be overwritten using the backgroundImage and foregroundImage as per the Yoda example, but it doesn't show how you can render your own component instead.
> 
> Please check this link: https://github.com/netguru/sticky-parallax-header/blob/HEAD/docs/CUSTOM.md
> 
> I have managed to create a custom header using the code as example on the above link.

Not really related to the `renderBody` prop.

**Comment by pi0trpietruszewski** [comment]
> I am also trying to figure out this exact same thing.
> 
> When you set headerType as `headerType="AvatarHeader"` we can pass a custom component using the foreground property in order to customize the content of the section. But when we set the headerType as `headerType="TabbedHeader"`, we are unable to pass a custom component, and thus we are stuck with the default layout in which we can only change the image and the title.
> 
> There has to be a way to be able to pass a custom component for `headerType="TabbedHeader"` as well.

To render body in `headerType="TabbedHeader"` use **'tabs'** prop.
Example:
```jsx
         <StickyParallaxHeader
          headerType="TabbedHeader"
          tabs={[
            {
              title: 'Popular',
              content: this.renderContent('Popular Quizes'),
            },
            {
              title: 'Product Design',
              content: this.renderContent('Product Design'),
            },
            {
              title: 'Development',
              content: this.renderContent('Development'),
            },
            {
              title: 'Project Management',
              content: this.renderContent('Project Management'),
            },
          ]}
        />
```

**Comment by yicru** [comment]
Has this problem been resolved?
The `renderBody` prop doesn't seem to be working in `TabbedHeader`.
I want to customize body in TabbedHeader.
![94142017-e5e37180-fe6d-11ea-9674-c11ed84e567c-2](https://user-images.githubusercontent.com/37892222/95539673-f4af5400-0a29-11eb-9522-d83a4d2edec6.png)

**Comment by 200610313** [comment]
> Has this problem been resolved?
> The `renderBody` prop doesn't seem to be working in `TabbedHeader`.
> I want to customize body in TabbedHeader.
> ![94142017-e5e37180-fe6d-11ea-9674-c11ed84e567c-2](https://user-images.githubusercontent.com/37892222/95539673-f4af5400-0a29-11eb-9522-d83a4d2edec6.png)

I'd like to know how to customize that part as well.  [Documentation](https://github.com/netguru/sticky-parallax-header/blob/HEAD/docs/CUSTOM.md) describes
![image](https://user-images.githubusercontent.com/41291228/98512955-18bcba00-22a2-11eb-9af5-020b001b49a0.png)

but I can't get it to work.

**Comment by ugrdursun** [comment]
> > Has this problem been resolved?
> > The `renderBody` prop doesn't seem to be working in `TabbedHeader`.
> > I want to customize body in TabbedHeader.
> > ![94142017-e5e37180-fe6d-11ea-9674-c11ed84e567c-2](https://user-images.githubusercontent.com/37892222/95539673-f4af5400-0a29-11eb-9522-d83a4d2edec6.png)
> 
> I believe you are referring the the background. I'd like to know how to customize that part as well. [Documentation](https://github.com/netguru/sticky-parallax-header/blob/HEAD/docs/CUSTOM.md) describes
> ![image](https://user-images.githubusercontent.com/41291228/98512955-18bcba00-22a2-11eb-9af5-020b001b49a0.png)
> 
> but I can't get it to work.

Have you solved the issue ?

**Comment by pi0trpietruszewski** [comment]
> > > Has this problem been resolved?
> > > The `renderBody` prop doesn't seem to be working in `TabbedHeader`.
> > > I want to customize body in TabbedHeader.
> > > ![94142017-e5e37180-fe6d-11ea-9674-c11ed84e567c-2](https://user-images.githubusercontent.com/37892222/95539673-f4af5400-0a29-11eb-9522-d83a4d2edec6.png)
> > 
> > 
> > I believe you are referring the the background. I'd like to know how to customize that part as well. [Documentation](https://github.com/netguru/sticky-parallax-header/blob/HEAD/docs/CUSTOM.md) describes
> > ![image](https://user-images.githubusercontent.com/41291228/98512955-18bcba00-22a2-11eb-9af5-020b001b49a0.png)
> > but I can't get it to work.
> 
> Have you solved the issue ?

To customize header content please use `StickyParallaxHeader` without headerType. 
TabbedHeader is predefined.


###(Example)[https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md#usage]

**Comment by pi0trpietruszewski** [comment]
###
