### ISSUE TITLE
Example usage with Function Component

### ISSUE THREAD

**Issue by AakashPat** [netguru/sticky-parallax-header#120]
I am currently struggling to get the header to work within a Function Component. The same piece of code works with a class component, but not as a function component. Any help is appreciated.

**Comment by IdaszakDaniel** [comment]
@AakashPat take a look at [additional examples](https://github.com/netguru/sticky-parallax-header/tree/master/example/src/screens/additionalExamples) directory, you can find function components there.

**Comment by AakashPat** [comment]
> @AakashPat take a look at [additional examples](https://github.com/netguru/sticky-parallax-header/tree/master/example/src/screens/additionalExamples) directory, you can find function components there.

Thanks!

**Comment by charitha95** [comment]
> @AakashPat take a look at [additional examples](https://github.com/netguru/sticky-parallax-header/tree/master/example/src/screens/additionalExamples) directory, you can find function components there.

This gives us a 404. Is it moved to somewhere?

**Comment by IdaszakDaniel** [comment]
@charitha95 additional examples were moved [here](https://github.com/netguru/sticky-parallax-header/tree/master/examples/reactNative/src/screens/additionalExamples)
