### ISSUE TITLE
horizontal Scroll not working in renderBody

### ISSUE THREAD

**Issue by crzycoder** [netguru/sticky-parallax-header#121]
I'm using `AvatarHeader` and inside the renderBody using `FlatList` horizontal but it's not working.

**Comment by kentplaza** [comment]
Same problem,  only can scroll vertically

**Comment by toutouli** [comment]
Same problem，Is there a solution to this problem？

**Comment by Ravn6472** [comment]
For anyone who still has this problem, as a workaround solution you can go to:
`node_modules/react-native-sticky-parallax-header/src/StickyParallaxHeader.js`
and turn off scrollEnabled in the <ScrollableTabView> props (line 413) to disable the tabs navigation.

**Comment by mateusz1913** [comment]
This bug occurs in legacy v0.4.x version. Check out v1.0.x release candidate, which has `scrollEnabled` prop available
