### ISSUE TITLE
TabbedHeader Tab Content Body should be different height for every Tab Content.

### ISSUE THREAD

**Issue by AakashPat** [netguru/sticky-parallax-header#122]
Currently, when we pass different content to tabs for the TabbedHeader, the container for the Tab Content/Body is of the same size (Largest one) across all tabs. Also, the Scroll value from others tabs get reflected in other tabs since the plugin utilizes the same ScrollView component to show all tab content.

**Comment by Patys** [comment]
Please check newest release: https://github.com/netguru/sticky-parallax-header/releases

**Comment by Kleinhummel** [comment]
I still have the issue that the ScrollView is longer than the TabContent. See this picture: The Red component is my tab content and I want to be only able to scroll to the end of this component:

![Sticky-Parallax-Header content height](https://user-images.githubusercontent.com/47432229/91655433-bfb9f400-eab0-11ea-9fbd-1ee6eeaf77ef.PNG)
