### ISSUE TITLE
Changing Statusbar style.

### ISSUE THREAD

**Issue by someAndroidDeveloper** [netguru/sticky-parallax-header#125]
Hi, i tried to use DetailsHeader but I need to set my own statusbar. is there a way to prevent the component from overriding it?

**Comment by pi0trpietruszewski** [comment]
@someAndroidDeveloper  
To override status bar, place **<StatusBar>** component below **<StickyParallaxHeader>**

`   <>
        <StickyParallaxHeader headerType={'AvatarHeader'} />
        <StatusBar barStyle="dark-content" backgroundColor="red" />
      </>
`

**Comment by TouqeerBinArbab** [comment]
thanks
