### ISSUE TITLE
Is there an onDisplayedTabChanged event on TabbedHeader?

### ISSUE THREAD

**Issue by Kleinhummel** [netguru/sticky-parallax-header#128]
An event would be cool, that is called every time the displayed tab is changed. It could be named `onTabChanged` and the argument for the handler function could be the index of the tab that is currently displayed.

**Comment by DimitrisTzimikas** [comment]
@Kleinhummel  Check that
`<StickyParallaxHeader
          onChangeTab={(i) => {
            console.log(i);
          }}......`

**Comment by pi0trpietruszewski** [comment]
> @Kleinhummel Check that
> `<StickyParallaxHeader onChangeTab={(i) => { console.log(i); }}......`
Yes, use this prop
` onChangeTab: (  from: number;
  i: number;
  ref: any;) => void;`

**Comment by pi0trpietruszewski** [comment]
I am closing issue, if it won't help feel free to reopen issue

**Comment by dungdt-pnc** [comment]
its doesnt work! Please check again @pi0trpietruszewski

**Comment by Vn-ChemGio** [comment]
> 
> 
> > @Kleinhummel Check that
> > `<StickyParallaxHeader onChangeTab={(i) => { console.log(i); }}......`
> 
> Yes, use this prop
> 
> ` onChangeTab: ( from: number; i: number; ref: any;) => void;`
> 
>     * from: index of source
> 
>     * i: current tab
> 
>     * ref: reference to current tab
you missing {  } in param list
Correct:  onChangeTab: ({ from: number; i: number; ref: any;}) => void;

**Comment by fedenelli** [comment]
This method is failing for me too.

I am trying to check when a user navigates between tabs to update each tab's content, but onChangeTab does not fire.

My props looks like this

```
tabs={[
        {
          title: 'Account',
          content: <Account focus={tab === 1} />,
        },
        {
          title: 'Movements',
          content: <Movements focus={tab === 1} />,
        },
        {
          title: 'Redeems',
          content: <Redeems focus={tab === 2} />,
        },
]}
 onChangeTab={a => {
        console.log('CHANGED TAB', a);
        return setTab(a.i);
}}
```

**Comment by fedenelli** [comment]
After inspecting the package, I can confirm that this is solved in the repo but the fix is not available in the latest npm release.

**Comment by JayantJoseph** [comment]
onChangeTab is not firing for me either. I tried using:
```
<StickyParallaxHeader
          headerType="TabbedHeader"
```
