### ISSUE TITLE
Set keyboardShouldPersistTabs to 'handled'

### ISSUE THREAD

**Issue by Kleinhummel** [netguru/sticky-parallax-header#129]
I have a TextInput in my tab content, but I can't press a button in the tab content when the keyboard is open. I found out that usually setting the keyboardShouldPersistTabs property of the ScrollView surrounding the button and the TextInput to 'handled' fixes the problem. Is it possible that the same problem is present here? I tried to set the keyboardShouldPersistTabs prop to 'handled'on the AnimatedScrollView component in the render function of the StickyParallaxHeader.js file, but this isn't changing anything...

**Comment by pi0trpietruszewski** [comment]
Added _keyboardShouldPersistTabs_ prop, avaiable in next release.

@Kleinhummel Could you explain in details what is wrong?
Or can you upload video with issue?

**Comment by pi0trpietruszewski** [comment]
`keyboardShouldPersistTabs` prop is avaiable

**Comment by mateusz1913** [comment]
`keyboardShouldPersistTabs` is available both in legacy 0.4.x and 1.0.x versions
