### ISSUE TITLE
[Help] How to fix 'Require cycles' warnings

### ISSUE THREAD

**Issue by amsiddh** [netguru/sticky-parallax-header#131]
First really thanks for this wonderful library.

I have followed custom header doc (i.e https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md) and below my StickyParallaxHeader code. 
```
<StickyParallaxHeader
        foreground={this.renderScoreView()}
        header={this.renderHeaderView()}
        parallaxHeight={this.getParallaxHeight()}
        headerHeight={52}
        headerSize={() => {}}
        onEndReached={() => {}}
        bounces={false}
        scrollEvent={Animated.event(
          [{nativeEvent: {contentOffset: {y: scroll}}}],
          {useNativeDriver: false},
        )}
        tabs={[
          {
            title: 'First Tab',
            content: <FirstTab data={this.props.items} />,
          },
          {
            title: 'Second Tab',
            content: (
              <SecondTab data={this.props.cards} />
            ),
          },
        ]}
        tabTextStyle={styles.tabText}
        tabTextActiveStyle={styles.tabActiveText}
        tabsContainerStyle={styles.tabContainer}
      />

```
Everything works proper as expected, but getting below warnings. Please help in removing this warnings.

> [Thu Sep 10 2020 13:18:54.213]  WARN     Require cycle: node_modules/react-native-sticky-parallax-header/src/index.js -> node_modules/react-native-sticky-parallax-header/src/predefinedComponents/index.js -> node_modules/react-native-sticky-parallax-header/src/predefinedComponents/AvatarHeader/AvatarHeader.js -> node_modules/react-native-sticky-parallax-header/src/index.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> [Thu Sep 10 2020 13:18:54.214]  WARN     Require cycle: node_modules/react-native-sticky-parallax-header/src/index.js -> node_modules/react-native-sticky-parallax-header/src/predefinedComponents/index.js -> node_modules/react-native-sticky-parallax-header/src/predefinedComponents/TabbedHeader/TabbedHeader.js -> node_modules/react-native-sticky-parallax-header/src/index.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> [Thu Sep 10 2020 13:18:54.214]  WARN     Require cycle: node_modules/react-native-sticky-parallax-header/src/index.js -> node_modules/react-native-sticky-parallax-header/src/predefinedComponents/index.js -> node_modules/react-native-sticky-parallax-header/src/predefinedComponents/DetailsHeader/DetailsHeader.js -> node_modules/react-native-sticky-parallax-header/src/index.js
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by grkemtneri** [comment]
same issue, did you find solution ?

**Comment by FatemeMirzaeii** [comment]
same issue

**Comment by Mugilan-Codes** [comment]
Can i solve this ?
