### ISSUE TITLE
title is cut off in AvatarHeader

### ISSUE THREAD

**Issue by Relax594** [netguru/sticky-parallax-header#138]
Fresh installed v0.3.1 with react-native 0.63.2 on Samsung Galaxy Tab S5e. Same experience on Google Pixel C. Working fine on Pixel 3a XL. Looks like an issue with bigger screen resolutions.

Poor Brandon gets his name cut off.

```
<>
  <StickyParallaxHeader headerType="AvatarHeader" />
</>
```

Looks like this:

**Samsung Galaxy Tab S5e**
![Screenshot_20200922-130841_TimeAttack](https://user-images.githubusercontent.com/22765758/93875169-c9f89800-fcd4-11ea-8683-ecda656feeee.jpg)

**Google Pixel C**
![grafik](https://user-images.githubusercontent.com/22765758/93876178-aa626f00-fcd6-11ea-8f50-e11e0dd712ea.png)

**Google Pixel 3a XL**
![grafik](https://user-images.githubusercontent.com/22765758/93876204-ba7a4e80-fcd6-11ea-9d1a-c69f36bec9d8.png)

**Comment by pi0trpietruszewski** [comment]
#144 Fixes this issue
