### ISSUE TITLE
DetailsHeader is missing props available in other types of header

### ISSUE THREAD

**Issue by pi0trpietruszewski** [netguru/sticky-parallax-header#146]
**DetailsHeader is missing props available in other types of header**

* **I'm submitting a ...**
  - [x] bug report

  - [ ] feature request

  - [ ] support request
  
The **_contentContainerStyle, scrollRef, keyboardShouldPersistTaps, refreshControl_** props are missing in `src/predefinedComponents/DetailsHeader/DetailsHeader.js`,  PropTypes, and `src/index.d.ts`

**Comment by anusha5695** [comment]
Can pick this as well @pi0trpietruszewski

**Comment by pi0trpietruszewski** [comment]
Fix in #241
