### ISSUE TITLE
AvatarHeader is missing props available in other types of header

### ISSUE THREAD

**Issue by pi0trpietruszewski** [netguru/sticky-parallax-header#147]
**AvatarHeader is missing props available in other types of header**

* **I'm submitting a ...**
  - [x] bug report

  - [ ] feature request

  - [ ] support request
  
The **_contentContainerStyle, scrollRef, keyboardShouldPersistTaps, refreshControl_** props are missing in `src/predefinedComponents/DetailsHeader/AvatarHeader.js`,  PropTypes, and `src/index.d.ts`

**Comment by bobsany16** [comment]
Hi, I was looking at this and saw that the `AvatarHeader.js` is in `/AvatarHeader/AvatarHeader.js`. Could you clarify ?

**Comment by bobsany16** [comment]
I would love to work on this. I will have a PR up by the end of the week :)

**Comment by pi0trpietruszewski** [comment]
Fix in #241
