### ISSUE TITLE
TabbedHeader is missing props available in other types of header, missing props in documentation

### ISSUE THREAD

**Issue by pi0trpietruszewski** [netguru/sticky-parallax-header#148]
**TabbedHeader is missing props available in other types of header**

* **I'm submitting a ...**
  - [x] bug report

  - [ ] feature request

  - [ ] support request
  
The **_contentContainerStyle, scrollRef, keyboardShouldPersistTaps, refreshControl, rememberTabScrollPosition_** props are missing in `src/predefinedComponents/DetailsHeader/TabbedHeader.js`,  PropTypes, and `src/index.d.ts`

**Comment by anusha5695** [comment]
Hello @pi0trpietruszewski , I can pick this
