### ISSUE TITLE
No children prop in docs, replace renderBody to children in predefinedComponents

### ISSUE THREAD

**Issue by pi0trpietruszewski** [netguru/sticky-parallax-header#149]
**No children prop in docs, add children prop in predefinedComponents**

* Add children prop in README.md
* Add children prop in `AvatarHeader, DetailsHeader` and types `src/index.d.ts`.

**Comment by Tilenozz** [comment]
When this feature will be avaiable ?

**Comment by pi0trpietruszewski** [comment]
fixed in #244
