### ISSUE TITLE
Support for FlatList

### ISSUE THREAD

**Issue by pi0trpietruszewski** [netguru/sticky-parallax-header#157]
**Support for FlatList**

* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request
  
* **If bug, used module version**

    0.4.0
 
  
* **What is the current behavior?**
 -On IOS, `FlatList` sometimes stuck, and user is unable to scroll down.
 -On Android `FlatList` is scrollable without Header moving.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
 - Open example
 - Select Quiz

* **Solution Idea**
 For non tabbed components we can try to detect `FlatList` and replace `ScrollableTabView` to `React.cloneElement()` cloned `FlatList`. But no idea what we can do with `TabbedHeader`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

IOS                                       |  Android
:-------------------------:|:-------------------------:
![ezgif-4-1726a70d0b12](https://user-images.githubusercontent.com/47576536/94555901-87970400-025c-11eb-9e04-728ca0fe2503.gif)|![ezgif-4-55827a9427c2](https://user-images.githubusercontent.com/47576536/94555798-6afacc00-025c-11eb-9142-47c36acc59b3.gif)

**Comment by phwed** [comment]
I am facing the same issue currently is there a way to resolve this?

**Comment by phwed** [comment]
> I am facing the same issue currently is there a way to resolve this?

never mind i solved it by added scrollEnabled={false} to the flatlist and moving my scroll logic to the Header as suggested

**Comment by SvenNussgruber** [comment]
@phwed Do you mind sharing how exactly you implemented the scroll logic in the Header? I'm trying to have a top text that disappears, a search bar underneath that stays stickied, and a sectionList underneath that but can't get it working properly.

**Comment by phwed** [comment]
@SvenNussgruber 
You can override the components with animated views as shown here 

const CutomHeaderScreen = () => {

  const renderHeader = () => {
    const opacity = scrollY.y.interpolate({
      inputRange: [0, 60, 90],
      outputRange: [0, 0, 1],
      extrapolate: 'clamp',
    })

    return (
      <View
        style={styles.headerCotainer}>
        <View style={styles.headerWrapper}>
          <TouchableOpacity onPress={() => {}>
            <Image
              style={styles.headerImage}
              resizeMode="contain"
              source={{
                uri: 'https://close.png',
              }}
            />
          </TouchableOpacity>
          <Animated.View style={{ opacity }}>
            <Text
              style={styles.headerText}>
              Baby Yoda
            </Text>
          </Animated.View>
        </View>
      </View>
    )
  }

  return (
    <StickyParallaxHeader
      headerType="TabbedHeader"
      header={renderHeader}
      scrollEvent={event(
        [{ nativeEvent: { contentOffset: { y: scrollY.y } } }],
        { useNativeDriver: false }
      )}
    />
  )
}


link to docs::
https://github.com/netguru/sticky-parallax-header/blob/master/docs/TABBEDHEADER.MD

**Comment by mateusz1913** [comment]
`FlatList`, `SectionList` & custom scroll components are supported in version 1.0.x
