### ISSUE TITLE
Support icon components instead of image source for header icons

### ISSUE THREAD

**Issue by aeife** [netguru/sticky-parallax-header#158]
Support icon components instead of image source for header icons

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request
  
* **Platform**
  - [x] ios
  - [x] android
  

* **What is the current behavior?**
TopLeftIcon and TopRightIcon only support image source. 

* **If is a feature request, What is the motivation / use case for changing the behavior?**
It would be easier and probably better looking if we could just reuse existing icon components like e.g. Ionicons.

* **Other information**
Tabs in the tabbedHeader already support a component for an icon.

**Comment by vividh** [comment]
I can work on this. Is it acceptable to overload the current props (`leftTopIcon` / `rightTopIcon`) to accept a React Element, or should it be separate props?
