### ISSUE TITLE
BackgroundImage is re-rendered every time the tab is switched.

### ISSUE THREAD

**Issue by yicru** [netguru/sticky-parallax-header#160]
**BackgroundImage is re-rendered every time the tab is switched.**

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request
  
* **If bug, used module version**

    4.0.0
  
* **Platform**
  - [x] ios
  - [ ] android
  

* **What is the current behavior?**
When I go back to the top and every time I switch tabs, the background image re-renders.

![ezgif-7-b9f4334072ca](https://user-images.githubusercontent.com/37892222/94755573-ed57cd00-03cf-11eb-9f4e-490441e940c2.gif)
(image url is "https://images.unsplash.com/photo-1459749411175-04bf5292ceea")

Please give me your advice if you have any ideas.

**Comment by brooksbecton** [comment]
I'd like to grab this one!
