### ISSUE TITLE
Show header only when scrolling

### ISSUE THREAD

**Issue by picknamexd** [netguru/sticky-parallax-header#162]
This is possible? I am using TabbedHeader and I would like the header to show only when the tabs touch the superopr parts.
I've seen some use the transparentHeadder prop but it doesn't work for me with TabbeddHeader

**Comment by IdaszakDaniel** [comment]
As far as I know, TransparentHeader is only implemented in Avatar header right now. You can check the [example of that](https://www.netguru.com/codestories/implement-an-app-store-header-in-react-native-with-sticky-parallax-library). I think your case should be possible to implement with the [custom header](https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md).

**Comment by picknamexd** [comment]
@IdaszakDaniel 
Great! i got what i needed but i have problem, tabs are hiding under header, is there any way to pin tabs under header?
