### ISSUE TITLE
Body being rendered under the header

### ISSUE THREAD

**Issue by Relax594** [netguru/sticky-parallax-header#169]
**Title**

Body going under the header

* **I'm submitting a ...**
  - [ X ] bug report
  - [  ] feature request
  - [  ] support request
  
* **If bug, used module version**

    0.4.0
  
* **Platform**
  - [ X ] ios
  - [ X ] android
  

* **What is the current behavior?**

The body gets rendered under the header once scrolling

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```
<StickyParallaxHeader
                headerType="AvatarHeader"
                renderBody={renderBody}
            />
```

```
const renderBody = () => {
        return (
            <View>
                {list.map((item, i) => (
                    <ListItem key={i} bottomDivider onPress={item.onPress}>
                        <Icon type="ionicon" name={item.icon} />
                        <ListItem.Content>
                            <ListItem.Title>{item.title}</ListItem.Title>
                        </ListItem.Content>
                        <ListItem.Chevron />
                    </ListItem>
                ))}
            </View>
        );
    };
```

First render:
<img src="https://user-images.githubusercontent.com/22765758/96346752-b6570c00-109d-11eb-8165-189570d9d0ff.png" width="50%" height="50%">

Scrolling up:
<img src="https://user-images.githubusercontent.com/22765758/96346731-a2aba580-109d-11eb-9253-53325af9d0d2.png" width="50%" height="50%">

Scrolling body up makes content stick behind the header:
<img src="https://user-images.githubusercontent.com/22765758/96346734-a4756900-109d-11eb-9f6e-c10558fd7309.png" width="50%" height="50%">

* **If is a feature request, What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rzinnatullin** [comment]
Same issue here.
Is there anything that should be done to make children of `StickyParallaxHeader` not go under the header?
![image](https://user-images.githubusercontent.com/11244866/98972368-2a1cf500-2534-11eb-981e-47097fa503ce.png)
![image](https://user-images.githubusercontent.com/11244866/98972389-33a65d00-2534-11eb-8594-aec5d4afa8d1.png)
![image](https://user-images.githubusercontent.com/11244866/98972414-3903a780-2534-11eb-9e7e-40331fbf2708.png)

**Comment by denissdubinin** [comment]
Still relevant issue
```
"@react-navigation/native": "^6.0.10",
react": "17.0.2",
"react-native": "0.68.1",
"react-native-gesture-handler": "^2.4.2",
"react-native-reanimated": "^2.8.0",
"react-native-sticky-parallax-header": "^0.4.2"
```

**Comment by mateusz1913** [comment]
Library's behavior is correct - content is scrolled and header part is stays at the top (is "sticky")
