### ISSUE TITLE
Blink backgroundImage

### ISSUE THREAD

**Issue by sachithamh** [netguru/sticky-parallax-header#172]
**Blink backgroundImage**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request
  
* **If bug, used module version**

    4.0.0
 

* **Platform**
  - [x] ios
  - [ ] android
  

* **What is the current behavior?**
blink background image when swipe up swipe down and also when changing tabs

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5784803/97099133-608cf000-16ab-11eb-9764-b1aa39a4e3ab.gif)

**Comment by brooksbecton** [comment]
I think I have the tab change blinking fixed here
https://github.com/netguru/sticky-parallax-header/pull/171
