### ISSUE TITLE
Setting custom background component

### ISSUE THREAD

**Issue by devByGelu** [netguru/sticky-parallax-header#173]
Hello, as of now we customize background image with `backgroundImage` property. But is there any way to pass a custom component for background? The [docs](https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md) mention that there exists a `background` property, but It doesn't seem to exist. 

Finally, I'd like to say that is an amazing package, thank you all contributors !

**Comment by maciejBudzinskiNG** [comment]
Hello @200610313. As for now, there is no way to add a custom background (as a component) to the header. Feel free to work on this feature or wait until we develop this feature. It's definitely something that we want to have as well.
