### ISSUE TITLE
Scroll deceleration

### ISSUE THREAD

**Issue by amosbastian** [netguru/sticky-parallax-header#175]
**Scroll deceleration**

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request
  
* **Platform**
  - [x] ios
  - [x] android
  
* **What is the current behavior?**

Currently when scrolling it decelerates too fast for my liking. I want to change this so it decelerates less quickly.

* **What is the motivation / use case for changing the behavior?**

It is different from the scrolling behaviour (deceleration) in the rest of the app when using a normal `ScrollView`. This is jarring for users and so I would like it to be consistent.

**Comment by maciejBudzinskiNG** [comment]
Hello @amosbastian. The new "decelerationRate" prop is a good idea. As it seems like a small change, we should be able to add this in one of the future releases.

**Comment by mateusz1913** [comment]
It's available in both legacy 0.4.x and 1.0.x versions
