### ISSUE TITLE
Async fetches blocks UI of the header

### ISSUE THREAD

**Issue by Hantex9** [netguru/sticky-parallax-header#176]
**Async fetches blocks UI interaction with the header**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] support request
  
  
* **Platform**
  - [x] ios
  - [x] android
  

* **I implemented a TabbedHeader with a FlatList inside, each time that the TabbedHeader reaches the end, i will fetch new datas from the server, but each async request (also with other async call to the server), the header blocks every UI interaction, also animations such as ScrollY, buttons, iteractions with Touchable etc. and it become available after fetch request is done. How can I solve this problem?**

* **I attached a gif where i show the problem, how can it be resolved?

**Comment by Hantex9** [comment]
EDIT:

Problem solved, it was a problem for my optimization

**Comment by maciejBudzinskiNG** [comment]
@Hantex9 Glad to hear that. I'm closing the issue.
