### ISSUE TITLE
Nested horizontal FlatList is not working

### ISSUE THREAD

**Issue by LaurenceSM10** [netguru/sticky-parallax-header#180]
**Title**

* **I'm submitting a ...**
  - [ ✓] bug report
  - [ ] feature request
  - [ ] support request
  
* **If bug, used module version**

    "react-native-sticky-parallax-header": "^0.4.0",
    "expo": "~39.0.2"
  
* **Platform**
  - [ ] ios
  - [ ✓] android
  

* **What is the current behavior?**
It is not possible to scroll a horizontal FlatList

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Add a horizontal FlatList inside the body

**Comment by poojagupta-simformsolutions** [comment]
Any update on this as we are also facing same issue when adding horizontal flatlist inside the body.

**Comment by virajpsimformsolutions** [comment]
import flatlist from react-native-gesture-handler.
Like: 
`import { FlatList } from 'react-native-gesture-handler';`

**Comment by mateusz1913** [comment]
Please provide link to reproducible repo (or Expo snack)
