### ISSUE TITLE
[BUG] headerType=DetailsHeader not update text "Design System" when scrollUp

### ISSUE THREAD

**Issue by Vn-ChemGio** [netguru/sticky-parallax-header#187]
**Title**

* **I'm submitting a ...**
  - [ ✓] bug report

  
* **If bug, used module version**

    0.4.0
  
* **Platform**
  - [ ] ios
  - [ ] android
  
When using        <StickyParallaxHeader headerType="DetailsHeader"
                              title={"@@@@@@@@@@@@@@@@"}
                              tag={"clgt"} 
/>
After scrollup to top text in header bar not update to tile, it only  is default value of title

**Comment by TomaszRej** [comment]
Pr #241  fixes that issue
