### ISSUE TITLE
After Navigation

### ISSUE THREAD

**Issue by ramkgunturu** [netguru/sticky-parallax-header#188]
**Title**

* **I'm submitting a ...**
  - [ ] bug report to android
  - [ ] feature request
  - [ ] support request
  
* **If bug, used module version**

    1.0.0
  
* **Platform**
  - [ ] ios
  - [ ] android --yes
  

* **What is the current behavior?**
* StatusBar is disabled when I move back or tab on other screens I dont know what happened ?
* 
when I press back screen or moving to other tabs from sticky parallex heade screen.StatusBar  of others screens are disabled  in android?

It seems content is not scrolling it is strucking and it seems statusbar is disable when i press or move to other screens.
Can some one please help me on this issue....

**Comment by pi0trpietruszewski** [comment]
https://reactnavigation.org/docs/status-bar/
