### ISSUE TITLE
Examples not work

### ISSUE THREAD

**Issue by HyperNovax** [netguru/sticky-parallax-header#197]
I try to run the example expo or react-native but I have an error.
Unable to resolve module @babel/runtime/helpers/interopRequireDefault from [...] @babel/runtime/helpers/interopRequireDefault could not be found within the project.

I install the package but always the same error. The file exist in node_modules.

**Comment by benrandja-akram** [comment]
@HyperNovax 
you need to install root folder packages first, 
```sh
yarn install
cd examples/expo
yarn install 
```

**Comment by pi0trpietruszewski** [comment]
Fixed in #236
