### ISSUE TITLE
scroll not responsive

### ISSUE THREAD

**Issue by hotaryuzaki** [netguru/sticky-parallax-header#212]
**scroll not responsive**

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request
  
* **Platform**
  - [ ] ios
  - [x] android
  

* **What is the current behavior?**
scroll not responsive, looks like animation was lag not smooth

![20210611_100931](https://user-images.githubusercontent.com/17826213/121625798-61d62600-ca9e-11eb-8f73-aee5405495e6.gif)

```
renderHeader = () => {
  const { goBack } = this.props.navigation;
  const produk = this.state.productDetail[0];
  const { scroll } = this.state;
  const opacity = scroll.interpolate({
    inputRange: [0, Layout.window.width/1.7+28, Layout.window.width/1.7+56], // SETUP KAPAN PARALAX HEADER MUNCUL
    outputRange: [0, 0, 1],
    extrapolate: 'clamp'
  });

  return (
     <View>
       <View style={[styles.parallaxLeft, { position: 'absolute', paddingHorizontal: 7 }]}>
        <Button transparent rounded style={styles.parallaxBack} onPress={() => goBack()}>
          <Icon.Ionicons
            name="md-arrow-back"
            size={24} color={Colors.colorLevel10}
          />
        </Button>
       </View>

	<Animated.View style={{ backgroundColor: Colors.colorLevel1, opacity }}>
	      <View style={styles.parallaxHeader}>
	        <View style={styles.parallaxLeft}>
	          <Button transparent rounded style={styles.parallaxBack} onPress={() => goBack()}>
	            <Icon.Ionicons
	              name="md-arrow-back"
	              size={24} color={Colors.colorLevel10}
	            />
	          </Button>
	        </View>
	        <View style={styles.parallaxRight}>
	          <Text style={styles.parallaxText}>
	            {this.strCutter(produk.product_name, 30)}
	          </Text>
	        </View>
              </View>
    	</Animated.View>
    </View>
  )
}

<StickyParalaxHeader
    header={this.renderHeader()}
    headerHeight={56}
    headerSize={() => {}}
    transparentHeader
    scrollEvent={Animated.event([{ nativeEvent: { contentOffset: { y: scroll } } }])}
>
  <ScrollView>
    <View>
    </View>
    <View>
    </View>
    <View>	
    </View>
  </ScrollView>
</StickyParalaxHeader>
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
app ver: 0.4.0
RN ver: 0.63

**Comment by brambang** [comment]
there is solution here, https://github.com/netguru/sticky-parallax-header/pull/182
this fix not merge to master yet.

but i found decelerationRate props is already exist, but why you not put this in readme??
`decelerationRate='normal'` fix this issue.
and i think is best to set 'normal' as default value since 'fast' created an issue

**Comment by hotaryuzaki** [comment]
> there is solution here, #182
> this fix not merge to master yet.
> 
> but i found decelerationRate props is already exist, but why you not put this in readme??
> `decelerationRate='normal'` fix this issue.
> and i think is best to set 'normal' as default value since 'fast' created an issue

Thanks it works
