### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by Shreyasc13** [netguru/sticky-parallax-header#216]
New to react-native here, couldn't figure out how to use sticky-parallax-header

Code:
App.js:

import React from 'react'
import StickyParallaxHeader from 'react-native-sticky-parallax-header'

const App= () => (
  <>
    <StickyParallaxHeader headerType="TabbedHeader" />
    {/* <StickyParallaxHeader headerType="AvatarHeader" /> */}
    {/* <StickyParallaxHeader headerType="DetailsHeader" /> */}
  </>
)

export default App

![image](https://user-images.githubusercontent.com/44752893/123156892-7eebfb00-d487-11eb-9253-bd245054cec0.png)

![image](https://user-images.githubusercontent.com/44752893/123156737-42b89a80-d487-11eb-9709-117737e9119c.png)

Error: 
44 |   mainText: string,
  45 |   labelText: string,
  46 |   elements: number,
> 47 |   imageSource: Image.propTypes.source,
  48 |   pressUser: func,
  49 | };
  50 |

**Comment by shivgarg5676** [comment]
Facing the same error. Is this specific to the latest version?

**Comment by TomaszRej** [comment]
Pr #241 fixes that issue.
