### ISSUE TITLE
Remove bounce effect while scrolling vertically and to make smooth scroll.

### ISSUE THREAD

**Issue by raikk** [netguru/sticky-parallax-header#217]
I would like to remove the bounce effect (it stuck) while scrolling the screen of the parallax header.

How to make it a smooth scroll?

try to fix this section but not working.
```
    const opacity = scroll.interpolate({
      inputRange: [0, 60, 100],
      outputRange: [0, 0, 1],
      extrapolate: 'extend'
    });
```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/12422925/124462771-a4460680-ddaf-11eb-8dd5-fee2eba85cf8.gif)

**Comment by pi0trpietruszewski** [comment]
Try `bounces={false}`

**Comment by brambang** [comment]
maybe this will fix your scrolling issue https://github.com/netguru/sticky-parallax-header/issues/212
