### ISSUE TITLE
Is it possible to insert a fullscreen image background that covers the header and foreground?

### ISSUE THREAD

**Issue by davidm03** [netguru/sticky-parallax-header#218]
**Allow fullscreen image backgrounds that cover the header and foreground**

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request
  
* **If bug, used module version**

    1.0.0
  
* **Platform**
  - [x] ios
  - [ ] android
  

* **What is the current behavior?**
Image background only covers the foreground area, with the header content remaining a solid color background. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **If is a feature request, What is the motivation / use case for changing the behavior?**
Allow the use of fullscreen image backgrounds that will cover both the header and foreground for a more attractive user interface. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by IdaszakDaniel** [comment]
Hi @davidm03, take a look at our example of implementing [App Store Header](https://www.netguru.com/blog/implement-an-app-store-header-in-react-native-with-sticky-parallax-library). You need to use "transparentHeader" prop. It makes header initially invisible and then it appears after scrolling.
