### ISSUE TITLE
TabbedHeader Content is visible under transparent Header

### ISSUE THREAD

**Issue by bastianspirek** [netguru/sticky-parallax-header#255]
I am using a transparent tabbed header. My page content starts right below the tab section, however when scrolling upwards, the content will be visible under the tab section and only hide under the header foreground. Is there anything I can do?
![image](https://user-images.githubusercontent.com/7038550/137905041-e904880d-9603-4a3d-842d-fc6fb7cceeeb.png)
![image](https://user-images.githubusercontent.com/7038550/137905209-92f7924a-0622-43a0-9d44-e8d4f9a6f5d1.png)

**Comment by mateusz1913** [comment]
It can be configured by setting `tabsContainerBackgroundColor` to the same color as header's background color
