### ISSUE TITLE
TypeScript is just wrong...

### ISSUE THREAD

**Issue by jzxchiang1** [netguru/sticky-parallax-header#258]
Plenty of bugs in `index.d.ts` for 0.4.1. Note, I'm using a custom header.

- `foreground` should be a `ReactElement`, not a component such as `() => ReactElement`
- `decelerationRate` should be optional
- `headerSize` and `scrollEvent` should be required (otherwise, it throws undefined is not a function)

**Comment by mateusz1913** [comment]
Consider checking out new v1.0.x release candidate, with fully rewritten API in TypeScript

```sh
yarn add react-native-sticky-parallax-header@rc
```
