### ISSUE TITLE
Animated Color Props for Custom Header

### ISSUE THREAD

**Issue by Ouzx** [netguru/sticky-parallax-header#261]
How can I use Animated Colors in custom header styling props? 
For example:
`tabsContainerStyle={{
          backgroundColor: scrollY.y.interpolate({
      inputRange: [0, 100],
      outputRange: [Colors.transparentBg, Colors.mainBG],
    }),
        }}`

I'm using TabbedHeader btw.

**Comment by mateusz1913** [comment]
@Ouzx with v1.0.x in `TabbedHeaderPager` (new `TabbedHeader`) we are using plain `FlatList`, so it's not possible now, to pass such animated style/value. Also with v1.0.x, we are sticking with react-native-reanimated instead of vanilla Animated API, but we'll work on supporting animated styles

**Comment by Digituals** [comment]
Hi! 
I have upgraded to v1.0x and now i need to set
`
tabUnderlineColor={color}
`
as an interpolate color and i dont know how to add it correct. Here is my code and my error.
Please give me an example
![Skärmavbild 2022-08-21 kl  17 51 23](https://user-images.githubusercontent.com/89830530/185800053-a432affb-0e66-4546-a1dc-80fc2d7dfc52.png)
![Skärmavbild 2022-08-21 kl  17 52 15](https://user-images.githubusercontent.com/89830530/185800056-e454a666-180c-4171-b395-10c030c8c5f2.png)
:

**Comment by mateusz1913** [comment]
Hi @Digituals, `react-native-sticky-parallax-header` is supporting animated (with Reanimated v2) color props from version `1.0.0-rc.8`. There's [dedicated docs section](https://netguru.github.io/sticky-parallax-header/docs/guides/animated-color-props) and you can also check how it works in [example repo](https://github.com/netguru/sticky-parallax-header/blob/master/example/src/screens/additionalExamples/TabbedHeaderWithAnimatedColors.tsx)
