### ISSUE TITLE
Add subTitle prop within Details Header.

### ISSUE THREAD

**Issue by SPellegrene** [netguru/sticky-parallax-header#287]
### Feature request

Currently the `title` prop is being passed through to the footer container, this is limiting the extensibility of the component. Passing a `subTitle` prop, similar to Avatar Header, would make it much easier to write custom text.

`<View style={styles.footerContainer}>
            {image && <Image source={image} style={styles.authorPhoto} resizeMode="contain" />}
            <Text numberOfLines={1} style={styles.authorName}>
              **{subTitle}**
            </Text>
 </View>`

**Comment by mateusz1913** [comment]
@SPellegrene  Implemented with https://github.com/netguru/sticky-parallax-header/pull/322 & available in `1.0.0-rc.4`
