### ISSUE TITLE
Can we use flatList instead of scrollview?

### ISSUE THREAD

**Issue by fencer-yd** [netguru/sticky-parallax-header#299]
### Feature request

I see that the core of content is still implemented using scrollview. Is it possible to replace scrollview with flatList?

**Comment by mateusz1913** [comment]
Hi @fencer-yd , you can check out v1.0.x release candidate which expose `ScrollView`, `FlatList` & `SectionList` header versions (we will promote it to stable in following weeks)

```sh
yarn add react-native-sticky-parallax-header@rc
```

**Comment by fencer-yd** [comment]
Thanks a lot for supporting flatList. This solved a higher problem for me.
