### ISSUE TITLE
Whether it can support virtual scrolling

### ISSUE THREAD

**Issue by fencer-yd** [netguru/sticky-parallax-header#328]
### Feature request

Can the tabHead coexist with the FlatList or can we customize the scrolling of the tabHead or can support the virtual scrolling of the content of the tabHead, this is important to me, can there be a solution?

**Comment by mateusz1913** [comment]
Hi @fencer-yd can you elaborate on that topic and possibly provide example of such behavior?

**Comment by fencer-yd** [comment]
I see that the content of tabHeader only supports ScrollView, but for the needs of long list scrolling or a too large number of  images lists, it seems that tabHeader does not support virtual scrolling, and you need to manually implement virtual scrolling, or implementing FlatList in tabHeader can also solve the problem. Can improve first load performance.

**Comment by mateusz1913** [comment]
@fencer-yd take a look at 1.0.0 release candidate which supports `ScrollView`, `FlatList` & `SectionList` components (in your case look for `TabbedHeaderList` & `TabbedHeaderPager`) https://netguru.github.io/sticky-parallax-header/docs/introduction/installation
With 1.0.0 release candidate you will also be able to create your own sticky layout experience https://netguru.github.io/sticky-parallax-header/docs/examples/custom-header
