### ISSUE TITLE
Show image in Avatar Header ScrollView after header collapse

### ISSUE THREAD

**Issue by Vn-ChemGio** [netguru/sticky-parallax-header#356]
### Environment

Library version: 1.0.0-rc.8
For this version
-The first :  After header collapsed, avatar does not show in header as well as example in 
![image](https://user-images.githubusercontent.com/25608423/189530266-141e64dd-9891-46eb-ac4e-d48e4a0f4be7.png)

- The second, If we unused props leftTopIcon, header after collapse has a redundant space 
![image](https://user-images.githubusercontent.com/25608423/189530370-f8dd2f17-2b66-48ff-ade9-789d8bba15cc.png)

Any body can help to fix

### Affected platforms

- [X] Android
- [X] iOS

### Current behavior

Expect result
![image](https://user-images.githubusercontent.com/25608423/189530392-f33a0d96-36a3-4129-a7c8-41eb7d8851b8.png)
Actual result
![image](https://user-images.githubusercontent.com/25608423/189530380-ed95696d-b0f5-44eb-a335-68c5cd63637c.png)

### Expected behavior

- When remove props leftTopIcon , redundant space should be removed
- After  header collapse, avatar can be  showed

### Reproduction

https://snack.expo.dev/@netguru_rnd/sticky-parallax-header-example?platform=android
See the example in snack

**Comment by Vn-ChemGio** [comment]
@mateusz1913 I''ve fix this issue, but can''t push update to github
Could you grant permission for me to push  new branch to this repo?

**Comment by mateusz1913** [comment]
👋 @Vn-ChemGio you can [create PR from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
