### ISSUE TITLE
Error using DetailsHeaderScrollView in Expo Web: createAnimatedComponent does not support stateless functional components; use a class component instead.

### ISSUE THREAD

**Issue by abbottdev** [netguru/sticky-parallax-header#379]
### Environment

Library version: 1.0.0-rc.9
OS version: Windows 11, Edge. 

### Affected platforms

- [ ] Android
- [ ] iOS

### Current behavior

![image](https://user-images.githubusercontent.com/3226335/212075188-4a8fe990-ae63-4732-a3bb-bfda19566385.png)

An error occurs viewing this in a Web browser. The error message is quite clear in that it should be using a class component instead of a functional component if using Reanimated: https://github.com/software-mansion/react-native-reanimated/issues/593

### Expected behavior

The error does not appear.

### Reproduction

Include a `DetailsHeaderScrollView` in a blank expo project and run the web compiler.

**Comment by mateusz1913** [comment]
Fix available in v1.1.1 🚀
