### ISSUE TITLE
renderBody for TabbedHeader not works

### ISSUE THREAD

**Issue by franjorub** [netguru/sticky-parallax-header#39]
I'm trying to replace the header of the example 
![imagen](https://user-images.githubusercontent.com/24401350/65351429-16873000-dbb6-11e9-8f9d-a35eece5e59f.png)
but the function I set is not setting the content that I want, it stills returning the example
`renderBody={(title) => <View><Text>Hello</Text></View>}`

**Comment by Karniej** [comment]
Hello, have you found a way to fixing it? 
If not, please let us now we'll investigate this issue.

**Comment by branislaav** [comment]
I have the same problem with a tabbed header, whatever I pass into renderBody prop header will not change.

**Comment by IdaszakDaniel** [comment]
In 0.2.1 version of the library we added new props to the Tabbed Header. Take a look at the [Tabbed Header Customisation doc](https://github.com/netguru/sticky-parallax-header/blob/master/docs/TABBEDHEADER.MD).
Now you can pass your content to `tabs`, pass custom header to the `header` prop and modify foreground.

**Comment by AakashPat** [comment]
The document you have linked to allows the user to only change the image and the title. We are looking for a way to pass an entire component.

**Comment by AakashPat** [comment]
Please check this link: https://github.com/netguru/sticky-parallax-header/blob/HEAD/docs/CUSTOM.md

I have managed to create a custom header using the code as example on the above link.

**Comment by sorxrob** [comment]
> In 0.2.1 version of the library we added new props to the Tabbed Header. Take a look at the [Tabbed Header Customisation doc](https://github.com/netguru/sticky-parallax-header/blob/master/docs/TABBEDHEADER.MD).
> Now you can pass your content to `tabs`, pass custom header to the `header` prop and modify foreground.

Why close? The link you provided is to modifying the header nav and not the related to `renderBody`.
