### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eladgel** [netguru/sticky-parallax-header#43]
Could you guys add an example of how to make this library work with FlatList?

**Comment by oferRounds** [comment]
+1

**Comment by davidwico** [comment]
What do you mean by working with FlatList? Please provide some code for better understanding

**Comment by pi0trpietruszewski** [comment]
@eladgel 
Please have a look: [How to handle FlatList](https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md#tips)
