### ISSUE TITLE
[TypeError: Cannot read property 'backgroundColor' of undefined]

### ISSUE THREAD

**Issue by sayem314** [netguru/sticky-parallax-header#52]
Error occured when tried to use custom header even with backgroundColor set to #000

**Comment by lesmo** [comment]
I figured it out. Your `header` component **must directly include a `style` prop with `backgroundColor`** or it will break:

```tsx
<StickyParalaxHeader
  background={
    <Hero source={{ uri: 'https://picsum.photos/seed/picsum/536/354' }} />
  }
  header={<TopNavigation style={{ backgroundColor: 'transparent' }} />}
  foreground={<Text>Some foreground</Text>}
/>
```

As you can see, even using `backgroundColor: 'transparent'` does the trick.

**Comment by sayem314** [comment]
@lesmo  Weird! Thanks for finding out the issue :) @netgurusupporter can you please solve this or document this better?
