### ISSUE TITLE
Hide sticky header

### ISSUE THREAD

**Issue by sayem314** [netguru/sticky-parallax-header#53]
How do I hide sticky header when the content position on top? I want to only display sticky header when user is scrolled a bit since there is image on the foreground and it doesn't look good with that.

**Comment by IdaszakDaniel** [comment]
hi @sayem314. Avatar Header has transparentHeader prop now. Take a look at similar implementation in [this article](https://www.netguru.com/codestories/implement-an-app-store-header-in-react-native-with-sticky-parallax-library)

**Comment by gulisashvili** [comment]
Hi It's still there even if i am using `transparentHeader` , it only makes `opacity: 0 `but it is still using height of header and i have unnecessory space  ... can u help me with that ?

**Comment by nolife08021** [comment]
@gulisashvili  did you found any solution for that?

**Comment by abhiburk** [comment]
same here. When I completely remove header prop then there is default netguru logo

**Comment by abhiburk** [comment]
we can use headerSize and headerHeight props to hide header

**Comment by martin-richter-uk** [comment]
I am also searching for a solution.

**Comment by martin-richter-uk** [comment]
headerHeight={headerHeight}
          transparentHeader={true}
          onMomentumScrollBegin={() => { setHeaderHeight(60) }}
          headerSize={() => {}}
          onEndReached={() => { setHeaderHeight(60) }}
          onTopReached={() => { setHeaderHeight(0) }}

This kind of worked for me.
