### ISSUE TITLE
Possible to use this library without the font dependency?

### ISSUE THREAD

**Issue by davitykale** [netguru/sticky-parallax-header#56]
I would love to be able to use this library without needing to include the fonts (or at least being able to override with my own).

**Comment by fend25** [comment]
yes, it is a really necessary thing due to there is only one font across the whole app in the design

**Comment by mdzyaan** [comment]
How can i disable this font??

**Comment by Patys** [comment]
Hey,
Font is removed, you can customize it on your own 👍
