### ISSUE TITLE
Tab container content issue.

### ISSUE THREAD

**Issue by sairam-405** [netguru/sticky-parallax-header#63]
Hi @team 
Its getting issue that when i have content in tab 1 and tab 4. When i goes to tab 1 its perfect and when i goes to tab 4 there is huge content so its scrolling proper when i comes back to tab 1 its getting issue that it takes tab4 content height but it should take tab1 content height.

How to resolve it?

**Comment by StephenBanz** [comment]
I tried setting the height of each tab using contentContainerStyle to the AnimatedScrolView, but contents inside overlap on each other. Tried solutions given here but it didn't help. will just leave the link here.
[Setting flex:1 on a ScrollView contentContainerStyle causes overlapping of components #4099](https://github.com/facebook/react-native/issues/4099) 
do let me know if someone comes across the solution

**Comment by pi0trpietruszewski** [comment]
Fixed in #118

**Comment by pi0trpietruszewski** [comment]
Fixed in #118
