### ISSUE TITLE
Tabs container initial padding

### ISSUE THREAD

**Issue by branislaav** [netguru/sticky-parallax-header#74]
I found issue that tab container has some initial padding from sides that can't be removed (when I add tabsWrapperStyle prop with 0 margin a padding nothing changes). 
<img width="393" alt="Screenshot 2020-04-18 at 19 55 29" src="https://user-images.githubusercontent.com/10597602/79645427-8f338680-81af-11ea-9a86-df40173d4f22.png">

**Comment by IdaszakDaniel** [comment]
Upgrade to the 0.2.0 version of the library and use tabsContainerStyle to change paddings. You can find detailed info about Tabs customisation there: [Custom tab styling](https://github.com/netguru/sticky-parallax-header/blob/master/docs/TABBEDHEADER.MD#custom-tab-styling)
