### ISSUE TITLE
All headerType in Tabbar

### ISSUE THREAD

**Issue by partitect** [netguru/sticky-parallax-header#78]
can be possible tabbar in all headerType?
I want use to tabbar in AvatarHeader

**Comment by IdaszakDaniel** [comment]
Tabbar is only available in TabbedHeader and when creating custom header. Take look at [TabbedHeader customisation](https://github.com/netguru/sticky-parallax-header/blob/master/docs/TABBEDHEADER.MD) or [Custom header example](https://github.com/netguru/sticky-parallax-header/blob/master/docs/CUSTOM.md)
