### ISSUE TITLE
title wrapper view height / padding

### ISSUE THREAD

**Issue by partitect** [netguru/sticky-parallax-header#79]
can be set possible padding / height in title wrapper like this
![indir](https://user-images.githubusercontent.com/6050956/80085310-b6e46f00-8560-11ea-999c-2987ff464171.jpeg)

**Comment by IdaszakDaniel** [comment]
In 0.2.1 version of the library you can use `parallaxHeight` prop to change height of the whole header foreground. Additionally you can pass custom component to the `foreground` prop.
