### ISSUE TITLE
change avatar image in tabbed header

### ISSUE THREAD

**Issue by partitect** [netguru/sticky-parallax-header#81]
How to change avatar image on tabbed header?
![indir (1)](https://user-images.githubusercontent.com/6050956/80087316-9964d480-8563-11ea-90ef-40625f6607b2.jpeg)

**Comment by IdaszakDaniel** [comment]
You can upgrade to the 0.2.0 version of the library and use foregroundImage prop to pass an image.
Check detailed doc with TabbedHeader customisation: 
[Custom header foreground](https://github.com/netguru/sticky-parallax-header/blob/master/docs/TABBEDHEADER.MD#custom-header-foreground)
