### ISSUE TITLE
typescript react native problem

### ISSUE THREAD

**Issue by mkalayci35** [netguru/sticky-parallax-header#84]
Unable to resolve module `../../assets/data/cards` from `node_modules/react-native-sticky-parallax-header/src/predefinedComponents/AvatarHeader/AvatarHeader.js`: 

None of these files exist:
  * node_modules/react-native-sticky-parallax-header/src/assets/data/cards(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-native-sticky-parallax-header/src/assets/data/cards/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by IdaszakDaniel** [comment]
Fixed in [version 0.2.1](https://github.com/netguru/sticky-parallax-header/releases/tag/v0.2.1)
