### ISSUE TITLE
Way to replace 'bounces' with refreshControl?

### ISSUE THREAD

**Issue by stephanoparaskeva** [netguru/sticky-parallax-header#89]
Adding something like 
```JavaScript
const [refreshing, setRefreshing] = useState(false);

<ScrollView
...
refreshControl={
<RefreshControl
  refreshing={refreshing}
  onRefresh={() => {
    setRefreshing(true);
    setTimeout(() => setRefreshing(false), 1000);
  }}
  progressViewOffset={400}
/>
}>
...
</ScrollView>
```

Will allow you to drag down for a refresh wheel, this is for refreshing content and is a must for situations where users want to update their content. Perhaps this can be added if the user wants the native scrollView bounce effect with a refreshControl (instead of 'bounces')

**Comment by IdaszakDaniel** [comment]
@stephanoparaskeva Would be great if you could create pull request

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva Would be great if you could create pull request

I'm only running the package after deleting the whole 'predefinedComponents' folder and changing switch in index.js to just return default. So I cannot make any PR's as my version is completely incompatible. Without these changes; I'm afraid that the package does not run for me

**Comment by IdaszakDaniel** [comment]
@stephanoparaskeva release 0.2.1 should fix recent issue with assets directory missing. Try using this version and in case of another problems - create issue with detailed information about your app.

I'm leaving this issue opened as we still want refeshControl to be implemented.

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva release 0.2.1 should fix recent issue with assets directory missing. Try using this version and in case of another problems - create issue with detailed information about your app.
> 
> I'm leaving this issue opened as we still want refeshControl to be implemented.

Can you point me to the parts of the code:
- That you can add refresh control
- That you can change deceleration rate of scroll
- That you can allow native scrollView bounce

**Comment by IdaszakDaniel** [comment]
@stephanoparaskeva https://github.com/netguru/sticky-parallax-header/blob/master/src/StickyParallaxHeader.js#L316
this is the main ScrollView used by all of the predefined components such as Tabbed Header

**Comment by DimitrisTzimikas** [comment]
In StickyParallaxHeader.js add:
```javascript 
 34: const { initialPage, refreshing } = this.props
 48: refreshing: refreshing,

169: onRefreshHandler = ()=>{
170:   const { onRefresh } = this.props
171:   return onRefresh && onRefresh()
172:
173: }

346:   refreshing,
347:   onRefresh
348: } = this.props

375: refreshControl={
376:  onRefresh? <RefreshControl refreshing={refreshing} onRefresh={()=>this.onRefreshHandler()} />: null
377: }

464: onRefresh: func,
465: refreshing: bool,
```

Does this approach expose the onRefresh to the user?

**Comment by pi0trpietruszewski** [comment]
#141 Will be available in next release
