### ISSUE TITLE
@types/react-native-sticky-parallax-header

### ISSUE THREAD

**Issue by mkalayci35** [netguru/sticky-parallax-header#95]
Try `npm install @types/react-native-sticky-parallax-header` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-sticky-parallax-header'

Can you do something for that ? 

Thank you, good work

**Comment by Patys** [comment]
Please check out: https://github.com/netguru/sticky-parallax-header/blob/master/src/index.d.ts
