### ISSUE TITLE
transparentHeader prop not working well with tabs

### ISSUE THREAD

**Issue by branislaav** [netguru/sticky-parallax-header#97]
transparentHeader prop in combination with tabs will overlay tab bar when srolled.

**Comment by pwysowski** [comment]
Hi @branislaav, could you provide more info about the problem - some screenshots or reproduction steps would be very helpful. 🙂

**Comment by branislaav** [comment]
Hi, @pwysowski, I have foreground with image and additional info,
but also need header to be transparent on top of image and when scolled to tabs it will interpolate its backgound to white and tabs will stick under header.
But right now when I use transparentHeader prop with custom header with tabs, header will overlay tabs when scrolled.
Is there a way to achieve this effect ?

![Simulator Screen Shot - iPhone 11 - 2020-08-10 at 15 03 04](https://user-images.githubusercontent.com/10597602/89786324-0785d500-db1c-11ea-8a48-da79c3aa348c.png)
![Simulator Screen Shot - iPhone 11 - 2020-08-10 at 15 03 13](https://user-images.githubusercontent.com/10597602/89786332-0b195c00-db1c-11ea-8a9a-cc4c7fa3f97f.png)
![Simulator Screen Shot - iPhone 11 - 2020-08-10 at 15 04 30](https://user-images.githubusercontent.com/10597602/89786334-0bb1f280-db1c-11ea-837f-11d547b14ad3.png)

**Comment by branislaav** [comment]
I managed to solve it with snapValue prop

**Comment by longhuynhthanh** [comment]
> I managed to solve it with snapValue prop

snapValue not work when I use headerType='TabbedHeader'

**Comment by virajpsimformsolutions** [comment]
> I managed to solve it with snapValue prop

Can share the details? How we can solve that issue?
